server:
  port: 7001

# GitHub配置（配置客户端id，回调地址）
github:
  client:
    id: 72d4490a6a78007d0d4b
    secret: 1202abb624dfac2e815ce9245208e59b13b4af48
  redirect:
    uri: http://localhost:7001/callback

# 配置Mysql数据库
spring:
  datasource:
    url:  jdbc:mysql://192.168.199.170:3306/community
    username: "root"
    password: "123456"
    driver-class-name: com.mysql.cj.jdbc.Driver

# 配置mybatis全局配置所在位置已经mapper配置文件所在位置
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: com.wool.community.mapper
  mapper-locations: classpath:/mapper/*.xml

# 配置ucloud的属性
ucloud:
  ufile:
#   公钥和私钥
    public: TOKEN_729a9bf1-acc5-44ec-a408-4dc94815cd51
    private: a53c60f5-e2ba-4baf-b2d3-d818849ebfe7
#   桶名（自己的域名）
    bucket: wool
#   前缀
    region: cn-bj
#   后缀
    suffix: ufileos.com
#  过期时间
    expires: 315360000



# 日志配置
logging:
  file: logs/community.log
#    日志文件大小
  file.max-size: 100MB
#    日志保存日期时间（单位天）
  file.max-history: 15


  #    日志级别
  level:
    root: info
    com:
      wool:
        community:
          mapper: debug
