server:
  port: 7001

# GitHub配置（配置客户端id，回调地址）
github:
  client:
    id: 72d4490a6a78007d0d4b
    secret: 1202abb624dfac2e815ce9245208e59b13b4af48
  redirect:
    uri: http://localhost:7001/callback

# 配置H2数据库
spring:
  datasource:
    url:  jdbc:mysql://192.168.1.104:3306/community
    username: "root"
    password: "123456"
    driver-class-name: com.mysql.cj.jdbc.Driver

# 配置mybatis全局配置所在位置已经mapper配置文件所在位置
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: com.wool.community.mapper
  mapper-locations: classpath:/mapper/*.xml
